"""projects

Revision ID: 06695a8acd9c
Revises: 4fc2a3dab90d
Create Date: 2026-08-09 19:34:09.166882

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06695a8acd9c'
down_revision: str | Sequence[str] | None = '4fc2a3dab90d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeline_entry_id', sa.UUID(), nullable=True),
    sa.Column('video_url', sa.String(length=2000), nullable=True),
    sa.Column('audience_override', postgresql.ARRAY(sa.Enum('recruiters', 'techies', 'investors', 'founders', 'personal', name='audience')), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'published', name='publish_status'), server_default='draft', nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['timeline_entry_id'], ['timeline_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index('ix_projects_status_publish_at', 'projects', ['status', 'publish_at'], unique=False)
    op.create_table('project_attachments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('PDF', 'PPT', 'IMAGE', name='project_attachment_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_topic_tags',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('topic_tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_tag_id'], ['topic_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'topic_tag_id')
    )
    op.add_column('timeline_entries', sa.Column('external_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_entries', 'external_url')
    op.drop_table('project_topic_tags')
    op.drop_table('project_attachments')
    op.drop_index('ix_projects_status_publish_at', table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
