"""add_admin_credentials_singleton

Revision ID: 3acf873925fa
Revises: 869fc8d8c856
Create Date: 2026-08-30 23:01:06.078411

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3acf873925fa'
down_revision: str | Sequence[str] | None = '869fc8d8c856'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('singleton_guard', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_guard')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_credentials')
    # ### end Alembic commands ###
