"""add crawler_hits table

Revision ID: 4d50231ae3d7
Revises: 7f3ad874fddf
Create Date: 2026-08-09 22:29:22.803841

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d50231ae3d7"
down_revision: str | Sequence[str] | None = "7f3ad874fddf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawler_hits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("path", sa.String(length=2000), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=False),
        sa.Column("agent_label", sa.String(length=50), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_crawler_hits_agent_label", "crawler_hits", ["agent_label"], unique=False)
    op.create_index("ix_crawler_hits_timestamp", "crawler_hits", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_crawler_hits_timestamp", table_name="crawler_hits")
    op.drop_index("ix_crawler_hits_agent_label", table_name="crawler_hits")
    op.drop_table("crawler_hits")
    # ### end Alembic commands ###
