"""overview: intro model and seeds

Revision ID: 4fc2a3dab90d
Revises: fe8ef9031bfb
Create Date: 2026-08-09 14:58:04.774320

"""
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fc2a3dab90d'
down_revision: str | Sequence[str] | None = 'fe8ef9031bfb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PUBLISH_STATUS_TYPE = postgresql.ENUM(
    'draft', 'scheduled', 'published',
    name='publish_status', create_type=False,
)

SEED_AUDIENCES = (
    "default",
    "recruiters",
    "techies",
    "investors",
    "founders",
    "personal",
)


def _intro_id(audience: str) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_URL, f"overview_intro/{audience}")


overview_intros_table = sa.table(
    "overview_intros",
    sa.column("id", sa.UUID()),
    sa.column("audience", sa.String()),
    sa.column("headline", sa.String()),
    sa.column("body", sa.Text()),
    sa.column("hero_image_key", sa.String()),
    sa.column("cta_label", sa.String()),
    sa.column("cta_url", sa.String()),
    sa.column("status", PUBLISH_STATUS_TYPE),
    sa.column("published_at", sa.DateTime(timezone=True)),
)


def upgrade() -> None:
    """Upgrade schema, then seed all six intro rows."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overview_intros',
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('hero_image_key', sa.String(length=2000), nullable=True),
    sa.Column('cta_label', sa.String(length=200), nullable=True),
    sa.Column('cta_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', PUBLISH_STATUS_TYPE, server_default='draft', nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience')
    )
    op.create_index('ix_overview_intros_audience', 'overview_intros', ['audience'], unique=True)
    op.create_index('ix_overview_intros_status_publish_at', 'overview_intros', ['status', 'publish_at'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        overview_intros_table,
        [
            {
                "id": _intro_id(aud),
                "audience": aud,
                "headline": f"Siddhesh Chaudhari — {aud.title()}",
                "body": f"Welcome! This is the **{aud}** view. Content is being prepared.",
                "hero_image_key": None,
                "cta_label": "Learn more" if aud != "default" else None,
                "cta_url": "/timeline" if aud != "default" else None,
                "status": "published",
                "published_at": datetime.now(UTC),
            }
            for aud in SEED_AUDIENCES
        ],
    )


def downgrade() -> None:
    """Delete seeded rows, then drop the table."""
    seeded_ids = [_intro_id(aud) for aud in SEED_AUDIENCES]
    op.execute(
        overview_intros_table.delete().where(
            overview_intros_table.c.id.in_(seeded_ids)
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_overview_intros_status_publish_at', table_name='overview_intros')
    op.drop_index('ix_overview_intros_audience', table_name='overview_intros')
    op.drop_table('overview_intros')
    # ### end Alembic commands ###
