"""thesis+posts

Revision ID: 6ea02da5e306
Revises: 762e5fa92af4
Create Date: 2026-08-09 20:17:04.134166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ea02da5e306"
down_revision: str | Sequence[str] | None = "762e5fa92af4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column(
            "platform",
            postgresql.ENUM("SUBSTACK", "MEDIUM", "YOUTUBE", "OTHER", name="post_platform"),
            nullable=False,
        ),
        sa.Column("published_date", sa.Date(), nullable=True),
        sa.Column(
            "collections",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "TECH_RABBITHOLE", "HOW_I_USE_AI", "VC_FOR_FOUNDERS", name="post_collection"
                )
            ),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "audience_override",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "recruiters",
                    "techies",
                    "investors",
                    "founders",
                    "personal",
                    name="audience",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "scheduled", "published", name="publish_status", create_type=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_posts_status_publish_at", "posts", ["status", "publish_at"], unique=False)
    op.create_table(
        "thesis_entries",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("drive_url", sa.String(length=2000), nullable=False),
        sa.Column("published_date", sa.Date(), nullable=False),
        sa.Column(
            "audience_override",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "recruiters",
                    "techies",
                    "investors",
                    "founders",
                    "personal",
                    name="audience",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "scheduled", "published", name="publish_status", create_type=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_thesis_entries_status_publish_at",
        "thesis_entries",
        ["status", "publish_at"],
        unique=False,
    )
    op.create_table(
        "post_topic_tags",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("topic_tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_tag_id"], ["topic_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "topic_tag_id"),
    )
    op.create_table(
        "thesis_topic_tags",
        sa.Column("thesis_id", sa.UUID(), nullable=False),
        sa.Column("topic_tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["thesis_id"], ["thesis_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_tag_id"], ["topic_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("thesis_id", "topic_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thesis_topic_tags")
    op.drop_table("post_topic_tags")
    op.drop_index("ix_thesis_entries_status_publish_at", table_name="thesis_entries")
    op.drop_table("thesis_entries")
    op.drop_index("ix_posts_status_publish_at", table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
