"""skills+certs

Revision ID: 762e5fa92af4
Revises: 06695a8acd9c
Create Date: 2026-08-09 19:57:24.965341

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "762e5fa92af4"
down_revision: str | Sequence[str] | None = "06695a8acd9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    AUDIENCE_TYPE = postgresql.ENUM(
        "recruiters",
        "techies",
        "investors",
        "founders",
        "personal",
        name="audience",
        create_type=False,
    )
    PUBLISH_STATUS_TYPE = postgresql.ENUM(
        "draft",
        "scheduled",
        "published",
        name="publish_status",
        create_type=False,
    )
    AUDIENCE_ARRAY = postgresql.ARRAY(AUDIENCE_TYPE)

    op.create_table(
        "certifications",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("issuer", sa.String(length=300), nullable=False),
        sa.Column(
            "kind", postgresql.ENUM("TECHNICAL", "BUSINESS", name="cert_kind"), nullable=False
        ),
        sa.Column("issued_date", sa.Date(), nullable=False),
        sa.Column("expires_date", sa.Date(), nullable=True),
        sa.Column("credential_url", sa.String(length=2000), nullable=True),
        sa.Column("file_key", sa.String(length=500), nullable=True),
        sa.Column(
            "file_type", postgresql.ENUM("PDF", "IMAGE", name="cert_file_type"), nullable=True
        ),
        sa.Column("audience_override", AUDIENCE_ARRAY, nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", PUBLISH_STATUS_TYPE, server_default="draft", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_certifications_status_publish_at",
        "certifications",
        ["status", "publish_at"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "section",
            postgresql.ENUM(
                "LANGUAGES", "TOOLS", "FRAMEWORKS", "AI", "BUSINESS", name="skill_section"
            ),
            nullable=False,
        ),
        sa.Column("subsection", sa.String(length=200), nullable=True),
        sa.Column("icon_slug", sa.String(length=100), nullable=True),
        sa.Column("icon_key", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certification_topic_tags",
        sa.Column("certification_id", sa.UUID(), nullable=False),
        sa.Column("topic_tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["certification_id"], ["certifications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_tag_id"], ["topic_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("certification_id", "topic_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certification_topic_tags")
    op.drop_table("skills")
    op.drop_index("ix_certifications_status_publish_at", table_name="certifications")
    op.drop_table("certifications")
    # ### end Alembic commands ###
