"""add is_pinned to publishable models

Revision ID: 7f3ad874fddf
Revises: 089089797167
Create Date: 2026-08-09 22:09:17.004653

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f3ad874fddf"
down_revision: str | Sequence[str] | None = "089089797167"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "certifications",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "collection_items",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "overview_intros",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "posts",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "projects",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "prose_pages",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "thesis_entries",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "timeline_entries",
        sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timeline_entries", "is_pinned")
    op.drop_column("thesis_entries", "is_pinned")
    op.drop_column("prose_pages", "is_pinned")
    op.drop_column("projects", "is_pinned")
    op.drop_column("posts", "is_pinned")
    op.drop_column("overview_intros", "is_pinned")
    op.drop_column("collection_items", "is_pinned")
    op.drop_column("certifications", "is_pinned")
    # ### end Alembic commands ###
