"""contact profile model and default seed

Revision ID: cc8619b8d037
Revises: 3acf873925fa
Create Date: 2026-09-02 22:33:44.745134

"""
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc8619b8d037'
down_revision: str | Sequence[str] | None = '3acf873925fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SEED_ID = uuid.uuid5(uuid.NAMESPACE_URL, "contact_profile/singleton")

SEED_PROFILE = {
    "id": SEED_ID,
    "email": "siddhesh@example.com",
    "linkedin_url": "https://www.linkedin.com/in/siddheshchaudhari/",
    "linkedin_label": "linkedin.com/in/siddheshchaudhari",
    "cal_url": "https://cal.com/siddhesh",
    "cal_label": "https://cal.com/siddhesh",
    "github_url": "https://github.com/siddhesh",
    "consent_text": "I consent to having my data stored for the purpose of this contact submission.",
}

contact_profiles_table = sa.table(
    "contact_profiles",
    sa.column("id", sa.UUID()),
    sa.column("email", sa.String()),
    sa.column("linkedin_url", sa.String()),
    sa.column("linkedin_label", sa.String()),
    sa.column("cal_url", sa.String()),
    sa.column("cal_label", sa.String()),
    sa.column("github_url", sa.String()),
    sa.column("consent_text", sa.Text()),
)


def upgrade() -> None:
    """Upgrade schema, then seed the singleton row."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_profiles',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('linkedin_url', sa.String(length=2000), nullable=False),
    sa.Column('linkedin_label', sa.String(length=300), nullable=False),
    sa.Column('cal_url', sa.String(length=2000), nullable=False),
    sa.Column('cal_label', sa.String(length=300), nullable=False),
    sa.Column('github_url', sa.String(length=2000), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('singleton_guard', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_guard')
    )
    # ### end Alembic commands ###

    op.bulk_insert(contact_profiles_table, [SEED_PROFILE])


def downgrade() -> None:
    """Delete the seeded row, then drop the table."""
    op.execute(
        contact_profiles_table.delete().where(contact_profiles_table.c.id == SEED_ID)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_profiles')
    # ### end Alembic commands ###
