"""relevance: audience tag map

Revision ID: cf9af7fc8db5
Revises: fb100e58ff80
Create Date: 2026-08-09 04:25:09.374851

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf9af7fc8db5"
down_revision: str | Sequence[str] | None = "fb100e58ff80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The native enum type already exists (core foundations migration); never
# re-create it here.
AUDIENCE_TYPE = postgresql.ENUM(
    "recruiters",
    "techies",
    "investors",
    "founders",
    "personal",
    name="audience",
    create_type=False,
)

# Seed vocabulary. Fixed uuid5 ids keep downgrade surgical and re-runs
# deterministic.
SEED_TAG_SLUGS = (
    "engineering",
    "consulting",
    "ai",
    "startup",
    "fundraising",
    "leadership",
    "books",
    "anime",
    "hobbies",
    "fitness",
)

SEED_MAP: dict[str, tuple[str, ...]] = {
    "recruiters": ("engineering", "consulting", "leadership"),
    "techies": ("ai", "engineering"),
    "investors": ("startup", "fundraising"),
    "founders": ("startup", "fundraising", "consulting"),
    "personal": ("books", "anime", "hobbies", "fitness"),
}


def _tag_id(slug: str) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_URL, slug)


def _map_row_id(audience: str, slug: str) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_URL, f"audience_tag_map/{audience}/{slug}")


topic_tags_table = sa.table(
    "topic_tags",
    sa.column("id", sa.UUID()),
    sa.column("slug", sa.String()),
    sa.column("label", sa.String()),
    sa.column("description", sa.Text()),
)

audience_tag_map_table = sa.table(
    "audience_tag_map",
    sa.column("id", sa.UUID()),
    sa.column("audience", AUDIENCE_TYPE),
    sa.column("topic_tag_id", sa.UUID()),
)


def upgrade() -> None:
    """Upgrade schema, then seed: the feature must be demonstrable before
    any hand configuration (TD-18)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audience_tag_map",
        sa.Column("audience", AUDIENCE_TYPE, nullable=False),
        sa.Column("topic_tag_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["topic_tag_id"], ["topic_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audience", "topic_tag_id", name="uq_audience_tag_map_audience_tag"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        topic_tags_table,
        [
            {"id": _tag_id(slug), "slug": slug, "label": slug.capitalize(), "description": ""}
            for slug in SEED_TAG_SLUGS
        ],
    )
    op.bulk_insert(
        audience_tag_map_table,
        [
            {"id": _map_row_id(audience, slug), "audience": audience, "topic_tag_id": _tag_id(slug)}
            for audience, slugs in SEED_MAP.items()
            for slug in slugs
        ],
    )


def downgrade() -> None:
    """Delete seeded rows first (FK order), then drop the table."""
    seeded_tag_ids = [_tag_id(slug) for slug in SEED_TAG_SLUGS]
    op.execute(
        audience_tag_map_table.delete().where(
            audience_tag_map_table.c.topic_tag_id.in_(seeded_tag_ids)
        )
    )
    op.execute(topic_tags_table.delete().where(topic_tags_table.c.id.in_(seeded_tag_ids)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audience_tag_map")
    # ### end Alembic commands ###
