"""core foundations: enums, topic tags

Revision ID: d902650351c6
Revises: 
Create Date: 2026-08-09 03:48:06.940575

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd902650351c6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native Postgres enum types. No column consumes them in this migration yet
# (publish_status arrives with the first publishable feature model, audience
# as ARRAY in TD-20), so autogenerate cannot see them — created by hand.
# Adding a VALUE later requires a hand-written ALTER TYPE (conventions 7).
AUDIENCE_TYPE = sa.Enum(
    "recruiters", "techies", "investors", "founders", "personal", name="audience"
)
PUBLISH_STATUS_TYPE = sa.Enum("draft", "scheduled", "published", name="publish_status")


def upgrade() -> None:
    """Upgrade schema."""
    AUDIENCE_TYPE.create(op.get_bind(), checkfirst=True)
    PUBLISH_STATUS_TYPE.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_tags',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.CheckConstraint('slug = lower(slug)', name='ck_topic_tags_slug_lowercase'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_tags_slug'), 'topic_tags', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_tags_slug'), table_name='topic_tags')
    op.drop_table('topic_tags')
    # ### end Alembic commands ###
    PUBLISH_STATUS_TYPE.drop(op.get_bind(), checkfirst=True)
    AUDIENCE_TYPE.drop(op.get_bind(), checkfirst=True)
