"""collections+prose

Revision ID: fbcad7943a73
Revises: 6ea02da5e306
Create Date: 2026-08-09 20:33:15.343354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbcad7943a73"
down_revision: str | Sequence[str] | None = "6ea02da5e306"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_items",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("creator", sa.String(length=300), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM("BOOK", "ANIME", "MANHWA", name="collection_kind"),
            nullable=False,
        ),
        sa.Column("section", sa.String(length=100), nullable=True),
        sa.Column("cover_key", sa.String(length=500), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column(
            "external_source",
            postgresql.ENUM("OPEN_LIBRARY", "JIKAN", "MANUAL", name="external_source"),
            nullable=True,
        ),
        sa.Column(
            "status_",
            postgresql.ENUM("READING", "COMPLETED", "WANT_TO_READ", name="collection_status"),
            nullable=True,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "scheduled", "published", name="publish_status", create_type=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collection_items_status_publish_at",
        "collection_items",
        ["status", "publish_at"],
        unique=False,
    )
    op.create_table(
        "prose_pages",
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "group",
            postgresql.ENUM("HOBBIES", "WORK_VIEWS", "INVESTOR_INTRO", name="prose_group"),
            nullable=False,
        ),
        sa.Column("cta_label", sa.String(length=200), nullable=True),
        sa.Column("cta_url", sa.String(length=2000), nullable=True),
        sa.Column(
            "audience_override",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "recruiters",
                    "techies",
                    "investors",
                    "founders",
                    "personal",
                    name="audience",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "scheduled", "published", name="publish_status", create_type=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prose_pages_slug"), "prose_pages", ["slug"], unique=True)
    op.create_index(
        "ix_prose_pages_status_publish_at", "prose_pages", ["status", "publish_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prose_pages_status_publish_at", table_name="prose_pages")
    op.drop_index(op.f("ix_prose_pages_slug"), table_name="prose_pages")
    op.drop_table("prose_pages")
    op.drop_index("ix_collection_items_status_publish_at", table_name="collection_items")
    op.drop_table("collection_items")
    # ### end Alembic commands ###
