"""timeline feature: entries model and association table

Revision ID: fe8ef9031bfb
Revises: cf9af7fc8db5
Create Date: 2026-08-09 14:29:33.216027

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe8ef9031bfb'
down_revision: str | Sequence[str] | None = 'cf9af7fc8db5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native enums already exist (core foundations migration); never re-create.
AUDIENCE_TYPE = postgresql.ENUM(
    'recruiters', 'techies', 'investors', 'founders', 'personal',
    name='audience', create_type=False,
)
PUBLISH_STATUS_TYPE = postgresql.ENUM(
    'draft', 'scheduled', 'published',
    name='publish_status', create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_entries',
    sa.Column('kind', postgresql.ENUM('EDUCATION', 'EXPERIENCE', name='timeline_kind'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organisation', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_override', postgresql.ARRAY(AUDIENCE_TYPE), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', PUBLISH_STATUS_TYPE, server_default='draft', nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publishable_status_publish_at', 'timeline_entries', ['status', 'publish_at'], unique=False)
    op.create_index('ix_timeline_start_date', 'timeline_entries', [sa.literal_column('start_date DESC')], unique=False)
    op.create_table('timeline_topic_tags',
    sa.Column('timeline_entry_id', sa.UUID(), nullable=False),
    sa.Column('topic_tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_entry_id'], ['timeline_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_tag_id'], ['topic_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timeline_entry_id', 'topic_tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_topic_tags')
    op.drop_index('ix_timeline_start_date', table_name='timeline_entries')
    op.drop_index('ix_publishable_status_publish_at', table_name='timeline_entries')
    op.drop_table('timeline_entries')
    # ### end Alembic commands ###
