/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api V1 Health */
        get: operations["api_v1_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_admin_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_certifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/{cert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_certifications__cert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_certifications_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_certifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/certifications/{cert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_certifications__cert_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_certifications__cert_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_certifications__cert_id__patch"];
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview/{audience}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_overview__audience__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_overview_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_overview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview/{intro_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_overview__intro_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_overview__intro_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_overview__intro_id__patch"];
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_posts__post_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_posts_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_posts__post_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_posts__post_id__patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_projects__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_projects_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/relevance/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map
         * @description Small, rarely changing: cache aggressively (conventions invariant 3
         *     ships this in every content page payload).
         */
        get: operations["get_map_api_v1_relevance_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/relevance/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get Map
         * @description Full current matrix: every audience present, empty ones included.
         */
        get: operations["admin_get_map_api_v1_admin_relevance_map_get"];
        /** Admin Update Map */
        put: operations["admin_update_map_api_v1_admin_relevance_map_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_skills_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/skills/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_skills__skill_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_skills__skill_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_skills__skill_id__patch"];
        trace?: never;
    };
    "/api/v1/thesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_thesis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/thesis/{thesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_thesis__thesis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/thesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_thesis_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_thesis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/thesis/{thesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_thesis__thesis_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_thesis__thesis_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_thesis__thesis_id__patch"];
        trace?: never;
    };
    "/api/v1/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public */
        get: operations["list_public_api_v1_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timeline/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public */
        get: operations["get_public_api_v1_timeline__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Admin */
        get: operations["list_admin_api_v1_admin_timeline_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_timeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/timeline/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin */
        get: operations["get_admin_api_v1_admin_timeline__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_admin_timeline__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_timeline__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_v1_admin_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_v1_admin_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_v1_admin_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Rename Tag */
        patch: operations["rename_tag_api_v1_admin_tags__tag_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminMapUpdate */
        AdminMapUpdate: {
            /** Mapping */
            mapping: {
                [key: string]: string[];
            };
        };
        /** AttachmentRef */
        AttachmentRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Sort Order */
            sort_order: number;
            /** Url */
            url: string;
        };
        /** CertificationAdmin */
        CertificationAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Issuer */
            issuer: string;
            /** Kind */
            kind: string;
            /**
             * Issued Date
             * Format: date
             */
            issued_date: string;
            /** Expires Date */
            expires_date: string | null;
            /** Credential Url */
            credential_url: string | null;
            /** File Key */
            file_key: string | null;
            /** File Type */
            file_type: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Audience Override */
            audience_override: string[] | null;
        };
        /** CertificationCreate */
        CertificationCreate: {
            /** Title */
            title: string;
            /** Issuer */
            issuer: string;
            /** Kind */
            kind: string;
            /**
             * Issued Date
             * Format: date
             */
            issued_date: string;
            /** Expires Date */
            expires_date?: string | null;
            /** Credential Url */
            credential_url?: string | null;
            /** File Key */
            file_key?: string | null;
            /** File Type */
            file_type?: string | null;
            /**
             * Tag Slugs
             * @default []
             */
            tag_slugs: string[];
            /** Audience Override */
            audience_override?: string[] | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** CertificationPublic */
        CertificationPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Issuer */
            issuer: string;
            /** Kind */
            kind: string;
            /**
             * Issued Date
             * Format: date
             */
            issued_date: string;
            /** Expires Date */
            expires_date: string | null;
            /** Credential Url */
            credential_url: string | null;
            /** File Key */
            file_key: string | null;
            /** File Type */
            file_type: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
        };
        /** CertificationUpdate */
        CertificationUpdate: {
            /** Title */
            title?: string | null;
            /** Issuer */
            issuer?: string | null;
            /** Kind */
            kind?: string | null;
            /** Issued Date */
            issued_date?: string | null;
            /** Expires Date */
            expires_date?: string | null;
            /** Credential Url */
            credential_url?: string | null;
            /** File Key */
            file_key?: string | null;
            /** File Type */
            file_type?: string | null;
            /** Tag Slugs */
            tag_slugs?: string[] | null;
            /** Audience Override */
            audience_override?: string[] | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** OverviewIntroAdmin */
        OverviewIntroAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Audience */
            audience: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Hero Image Key */
            hero_image_key: string | null;
            /** Cta Label */
            cta_label: string | null;
            /** Cta Url */
            cta_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** OverviewIntroCreate */
        OverviewIntroCreate: {
            /** Audience */
            audience: string;
            /**
             * Headline
             * @default
             */
            headline: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Hero Image Key */
            hero_image_key?: string | null;
            /** Cta Label */
            cta_label?: string | null;
            /** Cta Url */
            cta_url?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** OverviewIntroPublic */
        OverviewIntroPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Audience */
            audience: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Hero Image Key */
            hero_image_key: string | null;
            /** Cta Label */
            cta_label: string | null;
            /** Cta Url */
            cta_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OverviewIntroUpdate */
        OverviewIntroUpdate: {
            /** Headline */
            headline?: string | null;
            /** Body */
            body?: string | null;
            /** Hero Image Key */
            hero_image_key?: string | null;
            /** Cta Label */
            cta_label?: string | null;
            /** Cta Url */
            cta_url?: string | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /** PostAdmin */
        PostAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Url */
            url: string;
            /** Platform */
            platform: string;
            /** Published Date */
            published_date: string | null;
            /** Collections */
            collections: string[];
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Audience Override */
            audience_override?: string[] | null;
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** PostCreate */
        PostCreate: {
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Url */
            url: string;
            /** Platform */
            platform: string;
            /** Published Date */
            published_date?: string | null;
            /**
             * Collections
             * @default []
             */
            collections: string[];
            /**
             * Tag Slugs
             * @default []
             */
            tag_slugs: string[];
            /** Audience Override */
            audience_override?: string[] | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** PostPublic */
        PostPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Url */
            url: string;
            /** Platform */
            platform: string;
            /** Published Date */
            published_date: string | null;
            /** Collections */
            collections: string[];
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Audience Override */
            audience_override?: string[] | null;
        };
        /** PostUpdate */
        PostUpdate: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Url */
            url?: string | null;
            /** Platform */
            platform?: string | null;
            /** Published Date */
            published_date?: string | null;
            /** Collections */
            collections?: string[] | null;
            /** Tag Slugs */
            tag_slugs?: string[] | null;
            /** Audience Override */
            audience_override?: string[] | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /** ProjectAdmin */
        ProjectAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Description */
            description: string | null;
            /** Video Url */
            video_url: string | null;
            /** Timeline Entry Id */
            timeline_entry_id: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentRef"][];
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Audience Override */
            audience_override: string[] | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Timeline Entry Id */
            timeline_entry_id?: string | null;
            /** Video Url */
            video_url?: string | null;
            /**
             * Tag Slugs
             * @default []
             */
            tag_slugs: string[];
            /** Audience Override */
            audience_override?: string[] | null;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** ProjectPublic */
        ProjectPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Description */
            description: string | null;
            /** Video Url */
            video_url: string | null;
            /** Timeline Entry Id */
            timeline_entry_id: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["AttachmentRef"][];
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Slug */
            slug?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Timeline Entry Id */
            timeline_entry_id?: string | null;
            /** Video Url */
            video_url?: string | null;
            /** Tag Slugs */
            tag_slugs?: string[] | null;
            /** Audience Override */
            audience_override?: string[] | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /** SkillAdmin */
        SkillAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Subsection */
            subsection: string | null;
            /** Icon Slug */
            icon_slug: string | null;
            /** Icon Key */
            icon_key: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillCreate */
        SkillCreate: {
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Subsection */
            subsection?: string | null;
            /** Icon Slug */
            icon_slug?: string | null;
            /** Icon Key */
            icon_key?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** SkillPublic */
        SkillPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Subsection */
            subsection: string | null;
            /** Icon Slug */
            icon_slug: string | null;
            /** Icon Key */
            icon_key: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SkillUpdate */
        SkillUpdate: {
            /** Name */
            name?: string | null;
            /** Section */
            section?: string | null;
            /** Subsection */
            subsection?: string | null;
            /** Icon Slug */
            icon_slug?: string | null;
            /** Icon Key */
            icon_key?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** TagCreate */
        TagCreate: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
        };
        /** TagOut */
        TagOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
        };
        /** TagRef */
        TagRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Label */
            label: string;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Label */
            label?: string | null;
        };
        /** ThesisAdmin */
        ThesisAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Drive Url */
            drive_url: string;
            /**
             * Published Date
             * Format: date
             */
            published_date: string;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Audience Override */
            audience_override?: string[] | null;
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** ThesisCreate */
        ThesisCreate: {
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Drive Url */
            drive_url: string;
            /**
             * Published Date
             * Format: date
             */
            published_date: string;
            /**
             * Tag Slugs
             * @default []
             */
            tag_slugs: string[];
            /** Audience Override */
            audience_override?: string[] | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** ThesisPublic */
        ThesisPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Drive Url */
            drive_url: string;
            /**
             * Published Date
             * Format: date
             */
            published_date: string;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Audience Override */
            audience_override?: string[] | null;
        };
        /** ThesisUpdate */
        ThesisUpdate: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Drive Url */
            drive_url?: string | null;
            /** Published Date */
            published_date?: string | null;
            /** Tag Slugs */
            tag_slugs?: string[] | null;
            /** Audience Override */
            audience_override?: string[] | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /** TimelineEntryAdmin */
        TimelineEntryAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Organisation */
            organisation: string;
            /** Location */
            location: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Summary */
            summary: string | null;
            /** Highlights */
            highlights: string[] | null;
            /** External Url */
            external_url: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
            /** Status */
            status: string;
            /** Publish At */
            publish_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Audience Override */
            audience_override: string[] | null;
        };
        /** TimelineEntryCreate */
        TimelineEntryCreate: {
            kind: components["schemas"]["TimelineKind"];
            /** Title */
            title: string;
            /** Organisation */
            organisation: string;
            /** Location */
            location?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Summary */
            summary?: string | null;
            /** Highlights */
            highlights?: string[] | null;
            /** External Url */
            external_url?: string | null;
            /**
             * Tag Slugs
             * @default []
             */
            tag_slugs: string[];
            /** Audience Override */
            audience_override?: string[] | null;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Publish At */
            publish_at?: string | null;
        };
        /** TimelineEntryPublic */
        TimelineEntryPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Organisation */
            organisation: string;
            /** Location */
            location: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            /** Summary */
            summary: string | null;
            /** Highlights */
            highlights: string[] | null;
            /** External Url */
            external_url: string | null;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: components["schemas"]["TagRef"][];
        };
        /** TimelineEntryUpdate */
        TimelineEntryUpdate: {
            kind?: components["schemas"]["TimelineKind"] | null;
            /** Title */
            title?: string | null;
            /** Organisation */
            organisation?: string | null;
            /** Location */
            location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Summary */
            summary?: string | null;
            /** Highlights */
            highlights?: string[] | null;
            /** External Url */
            external_url?: string | null;
            /** Tag Slugs */
            tag_slugs?: string[] | null;
            /** Audience Override */
            audience_override?: string[] | null;
            /** Status */
            status?: string | null;
            /** Publish At */
            publish_at?: string | null;
        };
        /**
         * TimelineKind
         * @enum {string}
         */
        TimelineKind: "education" | "experience";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /** Code */
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    api_v1_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_api_v1_admin_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_public_api_v1_certifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationPublic"][];
                };
            };
        };
    };
    get_public_api_v1_certifications__cert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_certifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_certifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_certifications__cert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_certifications__cert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_certifications__cert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroPublic"][];
                };
            };
        };
    };
    get_public_api_v1_overview__audience__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audience: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_overview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewIntroCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_overview__intro_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intro_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_overview__intro_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intro_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_overview__intro_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intro_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverviewIntroUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewIntroAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_posts_get: {
        parameters: {
            query?: {
                collection?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_api_v1_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_posts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPublic"][];
                };
            };
        };
    };
    get_public_api_v1_projects__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_api_v1_relevance_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    admin_get_map_api_v1_admin_relevance_map_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    admin_update_map_api_v1_admin_relevance_map_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminMapUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPublic"][];
                };
            };
        };
    };
    list_admin_api_v1_admin_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_skills__skill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_skills__skill_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_skills__skill_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_thesis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisPublic"][];
                };
            };
        };
    };
    get_public_api_v1_thesis__thesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_thesis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_thesis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThesisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_thesis__thesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_thesis__thesis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_thesis__thesis_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thesis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThesisUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThesisAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_public_api_v1_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryPublic"][];
                };
            };
        };
    };
    get_public_api_v1_timeline__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_api_v1_admin_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryAdmin"][];
                };
            };
        };
    };
    create_api_v1_admin_timeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimelineEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_api_v1_admin_timeline__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_admin_timeline__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_timeline__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimelineEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntryAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_v1_admin_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag_api_v1_admin_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_v1_admin_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_tag_api_v1_admin_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
